version: "3.8"

services:
  database:
    build: ./database
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  server:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    develop:
      watch:
        - action: sync
          path: ./server
          target: /server
          ignore:
            - main
        - action: rebuild
          path: ./server/go.mod
    volumes:
      - assets:/api/assets
    # healthcheck:
    #   test: ["CMD", "./server/test.sh"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 2

  hub:
    build: ./hub
    container_name: hub
    restart: always
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 5s

  proxy:
    depends_on:
      - server
    build: ./proxy
    container_name: proxy
    ports:
      - 8000:8000

volumes:
  assets:
  db:
